# ------ root_path/dataset_name ------
# You should put the root path of your dataset below.
root_path: 'root_path/dataset_name'


# ------ Load Cache and Features ------
load_cache: False
load_pre_feat: False

# load_cache: True
# load_pre_feat: True


# ------ Hyperparameters ------
search_hp: True
#search_hp: False

search_scale: [7, 3]
search_step: [200, 20]

init_beta: 1
init_alpha: 1.17


# ------ Basic Config ------
dataset: 'eeg'
# You should set the few-shot number that you want to evaluate here and also set in the "eeg.py" file.
# The places where you should to change the few-shot number are specified in the eeg.py file.
shots: 16
#backbone: 'RN50'
#backbone: 'RN101'
#backbone: 'RN50x4'
backbone: 'RN50x16'
#ackbone: 'ViT-B/32'
#backbone: 'ViT-B/16'


lr: 0.0001
augment_epoch: 7  # Augmentation is not used in our project.
train_epoch: 20
